### ISSUE TITLE
Feature Request: Add sounds, view in bottom status bar

### ISSUE THREAD

**Issue by PKDmeDEV** [Raboro/obsidian-timer-plugin#1]
Hi,
Nice small plugin. I want to request two things if not too much
1. Notification sound when timer expires.
2. May be option for some background music.
3. a small widget in the bottom status bar to see timer.

Thanks

**Comment by Raboro** [comment]
Great idea. I don´t know how to add sounds to notifications. In the obsidian API - Notification class is no sound option. Do you know a way to add sounds. I see no solution to that.

**Comment by PKDmeDEV** [comment]
Hi,
You can have a look at implementation of another plugins like pomodoro
timer, which has sound options.

**Comment by captureMebutProbablyNot** [comment]
I literally came here to say the timer doesn't have sound. You kinda can't use it unless you're alerted that it's stopped. Currently there isn't an alert of any sort. But seeing this was posted in November and it hasn't changed makes me realize it's probably going to stay like this.

**Comment by Raboro** [comment]
I included timer in status bar in 1.0.6 and notification sound if timer expired in 1.0.5. Thanks for waiting.
